name: Docker Image CI

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.5.0
    
    - name: Iniciar sesión en Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Configurar CLI de Azure
      run: az configure --defaults acr=acrAndresMayor
      
    - name: Construir y etiquetar la imagen de Docker
      run: |
        docker build -t backend .
        docker tag backend acrAndresMayor.azurecr.io/backend:latest
        
    - name: Iniciar sesión en ACR
      run: az acr login --name acrAndresMayor

    - name: Subir imagen al ACR
      run: docker push acrAndresMayor.azurecr.io/acrAndresMayor:latest
      

